# シェルの設定
shell = "zsh"


[templates]
defer = "{% for file in files %}zsh-defer source \"{{ file }}\"\n{% endfor %}"

[plugins.zsh-defer]
github = "romkatv/zsh-defer"

[plugins.zsh-autosuggestions]
github = "zsh-users/zsh-autosuggestions"
use = ["{{ name }}.zsh"]

[plugins.zsh-completions]
github = "zsh-users/zsh-completions"
apply = ["defer"]

[plugins.zsh-history-substring-search]
github = "zsh-users/zsh-history-substring-search"

[plugins.zsh-vi-mode]
github = "jeffreytse/zsh-vi-mode"

[plugins.zsh-syntax-highlighting]
github = "zsh-users/zsh-syntax-highlighting"
